# -*- coding: utf-8 -*-
"""Sales - Python module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFievPsfygu6tKfUI0yz1Tj-vEyGxhDU
"""

# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import FuncFormatter

#global style setting

sns.set_theme(style="whitegrid", rc={
    "axes.spines.right": False,
    "axes.spines.top": False
})

plt.rcParams.update({
    "figure.dpi": 120,
    "axes.titlesize": 14,
    "axes.titleweight": "bold",
    "axes.labelsize": 11,
})

# Color palette
PALETTE_FINANCIAL = ["#3B82F6", "#F43F5E", "#10B981"]
PALETTE_CHANNEL   = ["#8B5CF6", "#06B6D4"]
COLOR_SINGLE      = "#6366F1"

# Functions for visualisations

# Forman large axis numbers as 'M' (millions) or 'k' (thousands)
def k_formatter(x, pos):
    if x >= 1_000_000:
        return f"{x / 1_000_000:.1f}M"
    elif x >= 1_000:
        return f"{int(x / 1_000)}k"
    return f"{int(x)}"

#  k_formatter to x- or y-axis of a given Axes object
def apply_k_formatter(ax, axis="y"):
    formatter = FuncFormatter(k_formatter)
    if axis == "y":
        ax.yaxis.set_major_formatter(formatter)
    else:
        ax.xaxis.set_major_formatter(formatter)

"""#Data Loading and Data Overview"""

# Commented out IPython magic to ensure Python compatibility.
# Connecting Google Drive
from google.colab import drive
drive.mount("/content/drive")

# Changing work folder
# %cd /content/drive/MyDrive/Mate

# Uploading datasets
products = pd.read_csv("products.csv")
events = pd.read_csv("events.csv")
countries = pd.read_csv("countries.csv")

print("PRODUCTS")
print(products.head())
print(products.shape)
print(products.info())

print("COUNTRIES")
print(countries.head())
print(countries.shape)
print(countries.info())

print("EVENTS")
print(events.head())
print(events.shape)
print(events.info())

"""# Data Cleaning and Transformation"""

# Standardize column names to snake_case across all tables
countries.columns = countries.columns.str.lower().str.replace("-", "_")
events.columns = events.columns.str.lower().str.replace(" ", "_")

print("MISSING VALUES \n")
print(f"Products NaN:\n{products.isna().sum()} \n")
print(f"Countries NaN:\n{countries.isna().sum()}\n")
print(f"Events NaN:\n{events.isna().sum()}\n")

# Percentage of missed values per column
print(f"Countries NaN %:\n{countries.isna().sum() / countries.shape[0] * 100}\n")
print(f"Events NaN %:\n{events.isna().sum() / events.shape[0] * 100}\n")

"""In the Events table, the missing values in the units_sold column have been removed as the percentage is very low;
however, in the country_code column, missing values account 6.17%—so we cannot simply delete them. We will therefore replace them with ‘Uknown’.
"""

# Drop rows where 'units_sold' is missing (very small share, <1%)
events = events.dropna(subset = ["units_sold"])

# Fill 'country_code' NaN with 'Unknown' (>5% share — cannot simply drop)
events['country_code'] = events["country_code"].fillna("Unknown")

# Fill missing geographic fields with 'Unknown'
fill_values = {"alpha_2": "Unknown", "region": "Unknown", "sub_region": "Unknown"}
countries.fillna(value=fill_values, inplace=True)

# Add new country - 'Uknown' to Countries table
unknown_country = pd.DataFrame({
    "name": ["Unknown"], "alpha_2": ["Unknown"], "alpha_3": ["Unknown"],
    "region": ["Unknown"], "sub_region": ["Unknown"]
})
countries = pd.concat([countries, unknown_country], ignore_index=True)

# Confirm no remaining nulls
print(f"Remaining NaN — Countries:{countries.isna().sum().sum()}")
print(f"Remaining NaN — Events:{events.isna().sum().sum()}")

# Convert date columns from string to datetime
events["order_date"] = pd.to_datetime(events["order_date"])
events["ship_date"]  = pd.to_datetime(events["ship_date"])

print(events.info())

# Inspect raw category values to spot casing/spacing inconsistencies
print(events['order_priority'].value_counts())
print(events['sales_channel'].value_counts())
print(events['country_code'].value_counts())

# Normalize categories values
events['order_priority'] = events['order_priority'].str.upper().str.replace(" ", "")
events['sales_channel'] = events['sales_channel'].str.lower()

print(events['order_priority'].value_counts())
print(events['sales_channel'].value_counts())

# Check for duplicates
print(f"Duplicates — Products:  {products.duplicated().sum()}")
print(f"Duplicates — Countries: {countries.duplicated().sum()}")
print(f"Duplicates — Events:    {events.duplicated().sum()}")

# Check key field uniqueness
print(f"Unique order_id:   {events["order_id"].nunique()}")
print(f"Unique product id: {products["id"].nunique()}")
print(f"Unique alpha_3:    {countries["alpha_3"].nunique()}")

# Check Numeric anomalies
print(events.describe())

"""# Data analysis and visualization

## Merge Data
"""

# Join tables into a single DataFrame
events_products = pd.merge(events, products, left_on="product_id", right_on="id" , how="inner")
sales = pd.merge(events_products, countries, left_on="country_code", right_on="alpha_3", how = "left")
sales.info()

sales.head()

# Drop duplicated columns and rename for clarity
sales = sales.drop(['id', 'country_code'], axis=1)
sales = sales.rename(columns={'name':'country_name'})

print(sales.columns)

# Company's key financial metrics

# add profit, total cost and revenue calculation columns
sales['revenue'] = sales['units_sold'] * sales['unit_price']
sales['total_cost'] = sales['units_sold'] * sales['unit_cost']
sales['profit'] = sales['revenue'] - sales['total_cost']

# Compute delivery time in days
sales["delivery_time"] = sales["ship_date"] - sales["order_date"]
sales["delivery_days"] = sales["delivery_time"] / pd.Timedelta(days=1)

# Extract time dimensions
sales["year"] = sales["order_date"].dt.year
sales["year_month"] = sales["order_date"].dt.to_period("M").astype(str)
sales["day_name"]   = sales["order_date"].dt.day_name()

"""## Key metrics"""

print(" KEY BUSINESS METRICS")
print(f"Total orders    : {sales['order_id'].nunique():,}")
print(f"Total revenue   : ${sales['revenue'].sum():,.0f}")
print(f"Total cost      : ${sales['total_cost'].sum():,.0f}")
print(f"Total profit    : ${sales['profit'].sum():,.0f}")
print(f"Countries served: {sales['alpha_3'].nunique() - 1}")   # exclude 'Unknown'

"""## Analysis by product category"""

# Set the format: two decimal places, thousands separator
pd.options.display.float_format = "{:,.2f}".format

# Financial metrics per product category
category_pivot = pd.pivot_table(
    sales,
    values=["revenue", 'total_cost', 'profit', 'units_sold'],
    index="item_type",
    aggfunc='sum'
    ).reset_index()

print(category_pivot)

# Financial performance by product category
categories_melted = pd.melt(
    category_pivot,
    id_vars=['item_type'],
    value_vars=['revenue', 'total_cost', 'profit'],
    var_name='Financial_Metric',
    value_name='Amount'
)
# Sorting categories by profit
sorted_categories = category_pivot.sort_values(by="profit", ascending=False)["item_type"]

fig, ax = plt.subplots(figsize=(14, 6))
sns.barplot(
    data=categories_melted,
    x="item_type", y="Amount",
    hue="Financial_Metric",
    palette=PALETTE_FINANCIAL,
    order= sorted_categories,
    ax=ax
)
ax.set_title("Financial Performance by Product Category")
ax.set_xlabel("Category")
ax.set_ylabel("Amount (USD)")
apply_k_formatter(ax, "y")

plt.tight_layout()
plt.show()

"""## Analysis by geography"""

# Financial metrics by region and country
geography_pivot = pd.pivot_table(
    sales,
    values=["revenue", "total_cost", "profit", "units_sold"],
    index=["region", "country_name"],
    aggfunc="sum",
    fill_value=0
).reset_index()


print(geography_pivot.head())

region_pivot = geography_pivot.groupby("region")[["profit", "revenue"]].sum().reset_index()
region_pivot = region_pivot.sort_values("profit", ascending=True)

# Profit by region
fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.barh(region_pivot["region"], region_pivot["profit"], color=COLOR_SINGLE)
for bar in bars:
    ax.text(
        bar.get_width() + 5e5, bar.get_y() + bar.get_height() / 2,
        k_formatter(bar.get_width(), None), va="center", fontsize=10
    )
ax.set_title("Total Profit by Region")
ax.set_xlabel("Profit (USD)")
ax.set_ylabel("Region")
apply_k_formatter(ax, "x")

plt.tight_layout()
plt.show()

# Top 7 countries by profit
top7_countries = (
    geography_pivot.groupby("country_name")["profit"]
    .sum()
    .nlargest(7)
    .sort_values()
    .reset_index()
)

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.barh(top7_countries["country_name"], top7_countries["profit"], color=COLOR_SINGLE)
for bar in bars:
    ax.text(
        bar.get_width() + 2e4, bar.get_y() + bar.get_height() / 2,
        k_formatter(bar.get_width(), None), va="center", fontsize=9
    )
ax.set_title("Top 7 Countries by Profit")
ax.set_xlabel("Total Profit (USD)")
ax.set_ylabel("")
apply_k_formatter(ax, "x")
plt.tight_layout()
plt.show()

"""## Analysis by sales channel"""

channel_pivot = pd.pivot_table(
    sales,
    values=["revenue", "total_cost", "profit", "units_sold"],
    index="sales_channel",
    aggfunc="sum"
).reset_index()

print(channel_pivot.head())

# Profit share — Online vs Offline
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(
    channel_pivot["profit"],
    labels=["Offline", "Online"],
    autopct="%1.1f%%",
    startangle=90,
    colors=PALETTE_CHANNEL
)

ax.set_title("Global Profit Share: Online vs Offline", pad=20)

plt.tight_layout()
plt.show()

# Channel comparison — Revenue, Cost, Profit
channel_melted = pd.melt(
    channel_pivot,
    id_vars=["sales_channel"],
    value_vars=["revenue", "total_cost", "profit"],
    var_name="Metric",
    value_name="Amount"
)

fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(data=channel_melted, x="sales_channel", y="Amount",
            hue="Metric", palette=PALETTE_FINANCIAL, ax=ax)
ax.set_title("Financial Metrics by Sales Channel")
ax.set_xlabel("Sales Channel")
ax.set_ylabel("Amount (USD)")
apply_k_formatter(ax, "y")
handles = ax.get_legend().legend_handles
ax.legend(handles, ["Revenue", "Total Cost", "Profit"], title="Metric")
plt.tight_layout()
plt.show()

"""## Delivery Time Analysis"""

# Average delivery time per category, region, and country

delivery_time_category = sales.groupby('item_type')['delivery_time'].mean().reset_index()
delivery_time_region = sales.groupby('region')['delivery_time'].mean().reset_index()
delivery_time_country = sales.groupby('country_name')['delivery_time'].mean().reset_index()

delivery_time_category['delivery_days'] = delivery_time_category['delivery_time'] / pd.Timedelta(days=1)
delivery_time_region['delivery_days'] = delivery_time_region['delivery_time'] / pd.Timedelta(days=1)
delivery_time_country['delivery_days'] = delivery_time_country['delivery_time'] / pd.Timedelta(days=1)

# Average delivery time by product category

# Sorting categories by delivery time
sorted_categories_by_time = delivery_time_category.sort_values(by="delivery_days", ascending=False)["item_type"]

fig, ax = plt.subplots(figsize=(14, 6))
bars_plot = sns.barplot(
    data=delivery_time_category,
    x="item_type", y="delivery_days",
    palette="mako",
    order= sorted_categories_by_time,
    ax=ax
)
for container in bars_plot.containers:
    bars_plot.bar_label(container, fmt="%.1f", padding=3, fontweight="bold")

ax.set_title("Average Delivery Time by Product Category")
ax.set_xlabel("Category")
ax.set_ylabel("Average Delivery Time (Days)")
ax.tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.show()

#Average delivery time by country

# Sorting countries by delivery time
sorted_countries_by_time = delivery_time_country.sort_values(by="delivery_days", ascending=False)["country_name"]

fig, ax = plt.subplots(figsize=(14, 6))
sns.barplot(
    data=delivery_time_country,
    x="country_name", y="delivery_days",
    color=COLOR_SINGLE,
    order=sorted_countries_by_time,
    ax=ax
)
ax.set_title("Average Delivery Time by Country")
ax.set_xlabel("Country")
ax.set_ylabel("Average Delivery Time (Days)")
ax.tick_params(axis="x", rotation=45, labelsize=8)

plt.tight_layout()
plt.show()

# Average delivery time by region
fig, ax = plt.subplots(figsize=(8, 5))
region_plot = sns.barplot(
    data=delivery_time_region,
    x="region", y="delivery_days",
    palette="mako", ax=ax
)
for container in region_plot.containers:
    region_plot.bar_label(container, fmt="%.1f", padding=3, fontweight="bold")
ax.set_title("Average Delivery Time by Region")
ax.set_xlabel("Region")
ax.set_ylabel("Average Delivery Time (Days)")

plt.tight_layout()
plt.show()

# Profit vs Delivery time Scatter plot
plt.figure(figsize=(8, 5))

sns.scatterplot(data=sales, y="profit", x="delivery_time", color= COLOR_SINGLE, alpha = 0.5)

plt.title("Profit vs Delivery time", fontsize=14, fontweight="bold")
plt.xlabel("Delivery time")
plt.ylabel("Profit")

plt.tight_layout()
plt.show()

"""## Sales trends over time"""

# Aggregate units sold by month and segment
sales_category_trend = sales.groupby(['year_month', 'item_type'], as_index=False)['units_sold'].sum()
sales_category_trend= sales_category_trend.sort_values('year_month')
all_dates_cat = sales_category_trend["year_month"].unique()

# Aggregate units sold by year and segment
sales_category_year_trend = sales.groupby(['year', 'item_type'])['units_sold'].sum().reset_index()
sales_category_year_trend = sales_category_year_trend.sort_values('year')
all_years = sales_category_year_trend["year"].unique()

# Yearly units sold by product category
fig, ax = plt.subplots(figsize=(15, 7))
sns.lineplot(
    data=sales_category_year_trend,
    x="year", y="units_sold",
    hue="item_type", marker="o", ax=ax
)
ax.set_title("Yearly Units Sold Trend by Product Category")
ax.set_xlabel("Timeline (Year)")
ax.set_ylabel("Units Sold")
ax.set_xticks(all_years)
ax.set_xticklabels(all_years)
apply_k_formatter(ax, "y")

plt.tight_layout()
plt.show()

# Top-7 countries with the highest sales of all time

top_countries = (
    sales.groupby("country_name")["units_sold"]
    .sum().nlargest(7).index
)
sales_top_countries  = sales[sales["country_name"].isin(top_countries)]
sales_country_trend  = (
    sales_top_countries.groupby(["year", "country_name"])["units_sold"]
    .sum().reset_index()
)
all_dates_country = sales_country_trend["year"].unique()

sales_region_trend = (
    sales.groupby(["year", "region"])["units_sold"]
    .sum().reset_index()
)
all_dates_region = sales_region_trend["year"].unique()

# Yearly units sold — Top 7 countries

fig, ax = plt.subplots(figsize=(15, 7))
sns.lineplot(
    data=sales_country_trend,
    x="year", y="units_sold",
    hue="country_name", marker="o", ax=ax
)
ax.set_title("Yearly Units Sold Trend by Country (Top 7)")
ax.set_xlabel("Timeline (Year)")
ax.set_ylabel("Units Sold")
ax.set_xticks(all_years)
ax.set_xticklabels(all_years)
apply_k_formatter(ax, "y")

plt.tight_layout()
plt.show()

# Yearly units sold by region
fig, ax = plt.subplots(figsize=(15, 7))
sns.lineplot(
    data=sales_region_trend,
    x="year", y="units_sold",
    hue="region", marker="o", palette="mako", ax=ax
)
ax.set_title("Yearly Units Sold Trend by Region")
ax.set_xlabel("Timeline (Year)")
ax.set_ylabel("Units Sold")
ax.set_xticks(all_years)
ax.set_xticklabels(all_years)
apply_k_formatter(ax, "y")

plt.tight_layout()
plt.show()

sales_day = sales.groupby('day_name')['units_sold'].sum().reset_index()
print(sales_day)

# Aggregate units sold by weekday and product category

sales_day_prod = sales.groupby(['day_name', 'item_type'])['units_sold'].sum().reset_index()

weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

sales_day_prod['day_name'] = pd.Categorical(
    sales_day_prod['day_name'], categories=weekday_order, ordered=True
    )
sales_day_prod = sales_day_prod.sort_values('day_name')

print(sales_day_prod)

# Weekly sales seasonality per category

g = sns.catplot(
    data=sales_day_prod,
    kind="bar",
    x="day_name", y="units_sold",
    col="item_type",
    col_wrap=3,
    height=4, aspect=1.5,
    color=COLOR_SINGLE,
    errorbar=None
)
g.set_axis_labels("Week Day", "Units Sold")
for ax in g.axes.flat:
    apply_k_formatter(ax, "y")

    # Clean subplot title — remove 'item_type = ' prefix
    title = ax.get_title().split("=")[-1].strip()
    ax.set_title(title, fontweight="bold", fontsize=12)
plt.tight_layout()

g.fig.subplots_adjust(top=0.9)
g.fig.suptitle("Weekly Sales Seasonality by Category", fontsize=16, fontweight="bold")
plt.show()

"""# Conclusions:

A total of **1,328 orders** were processed across **45 countries** during the analysis period. The total revenue reached 1.7 billion, while the **total profit amounted to 501.4 million**.

**Cosmetics, Office Supplies, and Household** products consistently generated the highest profits, whereas Fruits showed the lowest profitability.

**Europe** is the company’s core market and primary revenue driver, dominating sales volume throughout the entire period with monthly sales frequently ranging between 60k and 110k units. **Andorra, Ukraine, and Malta** were identified as the top-performing countries by total profit.

Both Online and Offline sales channels contributed almost equally to overall profit.

The **average delivery time** across all categories and regions ranged between **23 and 26 days**.

Hungary recorded the longest delivery times, while Croatia and the United Kingdom demonstrated the fastest delivery performance.

Among product categories, Personal Care had the shortest delivery times, while Cereals experienced the longest.

Overall, the scatter plot indicates a very **weak relationship between delivery time and profit**, suggesting that delivery duration has minimal impact on profitability.

Following a period of rapid growth between 2011 and 2012, the company's sales entered a stabilization phase, maintaining a consistent baseline over the longer term.
While overall trends show no aggressive upward or downward shifts post-2012, individual product categories—most notably Cosmetics, Household, Office Supplies, and Beverages—exhibit strong volatility, characterized by periodic and significant spikes in demand.

Most product categories maintain relatively stable weekday sales, with slight increases observed between **Saturday and Monday**.


The business demonstrates strong financial performance and a well-diversified sales structure, with Europe serving as the primary revenue-driving market. However, the analysis reveals several strategic improvement areas, including reducing dependence on the European market, stabilizing highly volatile product categories, improving low-performing segments, and optimizing logistics in countries with slower delivery times.

"""